apiVersion: v2
name: cert-manager
version: 0.1.0
description: Cert Manager helm chart

dependencies:
  - name: cert-manager
    version: v1.11.0
    repository: https://charts.jetstack.io
    alias: cert-manager